# Generated by Django 3.2 on 2023-08-08 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Поле не должно содержать символы:!#$%%^&*()=,<>?/\\|{}[]:; \n', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
