# Generated by Django 2.2.9 on 2022-12-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_auto_20221225_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
