# Generated by Django 2.2.16 on 2023-02-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230208_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': ('Группа',), 'verbose_name_plural': ('Группы',)},
        ),
    ]
