version: '3.3'

volumes:
  foodgram_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ./.env
    volumes:
      - foodgram_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-backend
    image: savich/foodgram_backend:latest
    env_file: ./.env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-frontend
    image: savich/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-nginx
    image: nginx:1.19.3
    restart: always
    depends_on:
      - db
      - frontend
      - backend
    ports:
      - 9080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
